package models

import "time"

// Market is the canonical internal representation of a prediction market.
// Every downstream component — equivalence detector, routing engine, server —
// works exclusively with this struct. Venue-specific raw structs are converted
// to Market by the adapter layer and never escape it.
type Market struct {
	// Identity
	ID      string // internal UUID generated by the adapter
	VenueID string // the ID the venue uses natively
	Venue   string // "kalshi" or "polymarket" — always lowercase
	Title   string // normalized question text (lowercase, stripped punctuation)

	// Pricing — all three stored explicitly for fast access
	YesBid  float64 // highest price someone will buy Yes (0.0 to 1.0)
	YesAsk  float64 // lowest price someone will sell Yes (0.0 to 1.0)
	YesMid  float64 // (YesBid + YesAsk) / 2 — midpoint price
	NoPrice float64 // 1.0 - YesMid — always derived, stored for convenience
	Spread  float64 // YesAsk - YesBid — tighter = healthier market

	// Liquidity
	Liquidity float64 // total $ available in order book
	Volume24h float64 // trading volume in last 24 hours

	// Timing
	ResolvesAt    time.Time // when the market closes and resolves
	ResolutionDate string   // YYYY-MM-DD (UTC) for same-date pairing; empty if unknown
	FetchedAt     time.Time // when we pulled this data (staleness detection)

	// Semantic fields for equivalence pre-filtering (same date + same underlying)
	Underlying string  // normalized asset, e.g. "SOL", "BTC"; empty if unknown
	StrikePrice float64 // threshold for price markets (e.g. "above 90" → 90); 0 if N/A or unknown

	// Metadata
	Category string // "politics", "economics", "crypto", "sports", "other"
	Status   string // "open", "closed", "resolved"

	// Debug — always preserve the original API response for auditability
	RawData interface{}
}

// MatchResult is the output of the equivalence detector for a single pair of
// markets — one from Kalshi, one from Polymarket.
type MatchResult struct {
	MarketA      Market
	MarketB      Market
	IsMatch      bool
	AreOpposites bool    // true when the markets are mirror images (GOP win = Dem loss)
	Confidence   float64 // 0.0 to 1.0
	Method       string  // "heuristic", "ai", or "heuristic+ai"
	Reasoning    string  // human-readable explanation of the decision
	Warnings     []string
	MatchedAt    time.Time
}

// VenueScore is the routing engine's score for one venue on a given market.
// All sub-scores are normalised to [0, 1] — higher is always better.
type VenueScore struct {
	Venue          string
	PriceScore     float64 // higher = better price for the requested side
	SpreadScore    float64 // higher = tighter spread (healthier market)
	LiquidityScore float64 // higher = deeper order book
	TotalScore     float64 // weighted combination of the three sub-scores
}

// RoutingDecision is the full output of the routing engine for a single
// hypothetical order.
type RoutingDecision struct {
	Market           Market
	OrderSide        string  // "yes" or "no"
	OrderSize        float64 // hypothetical $ amount
	RecommendedVenue string  // "kalshi" or "polymarket"
	Confidence       float64 // how clear-cut the decision was (0.0 to 1.0)
	VenueScores      []VenueScore
	Reasoning        string   // human-readable explanation
	Warnings         []string // caveats: stale data, missing info, tie-breaks
	DecidedAt        time.Time
}
